export const DD_PROFILE = 'https://ddragon.leagueoflegends.com/cdn/10.16.1/img/profileicon'
export const CHMP_IMG_SQUARE = 'https://ddragon.leagueoflegends.com/cdn/10.16.1/img/champion'
export const CHMP_INFO_URL = 'https://ddragon.leagueoflegends.com/cdn/10.16.1/data/en_US/champion.json'
export const CHMP_SPLASH_URL = 'https://ddragon.leagueoflegends.com/cdn/img/champion/loading'
export const SUMM_SPELL_URL = 'https://ddragon.leagueoflegends.com/cdn/10.16.1/img/spell'
export const ITEM_IMG_URL = 'https://ddragon.leagueoflegends.com/cdn/10.16.1/img/item'
export const EMPTY_IMG_URL = 'https://opgg-static.akamaized.net/images/pattern/opacity.1.png'
